"use client";
import React, { useEffect, useState } from "react";
import { usePathname, useRouter } from "next/navigation";
import { useAuth } from "../hooks/useAuth";
import { Metadata } from "next";
import { Press_Start_2P } from "next/font/google";

type Props = {
  children: JSX.Element;
};

const pressStartFont = Press_Start_2P({
  style: "normal",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "GTS Pokémon",
  description: "Generated by create next app",
};

export const Layout: React.FC<Props> = ({ children }) => {
  const router = useRouter();
  const pathname = usePathname();
  const { isAuthenticated, userHasInitialPokemons } = useAuth();

  useEffect(() => {
    const checkAuthAndRedirect = async () => {
      if (isAuthenticated()) {
        if (pathname === "/login") {
          router.push("/");
        } else if (userHasInitialPokemons()) {
          router.push("/");
        }
      } else {
        router.push("/login");
      }
    };

    checkAuthAndRedirect();
  }, [isAuthenticated, router]);

  return <div>{children}</div>;
};
